config/routes.rb
Rails.application.routes.draw do
  root to: "top_pages#top"
  get 'terms', to: 'top_pages#terms'
  get 'policy', to: 'top_pages#policy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  #Line Messaging
  post '/callback', to: 'linebot#callback' 
  
  get 'passed_lists', to: 'passed_lists#index'
  get 'sample_quiz', to: 'quizzes#sample_quiz'

  resources :users, only: %i[new create]
  resources :password_resets, only: %i[new create edit update]
  resource :profile, only: %i[show edit update]
  resources :test_categories, only: %i[index], as: :categories do
    get 'search_result', on: :collection
    
    resources :quizzes, only: %i[index show] do
      post 'calculate_score', on: :collection
    end
    resources :reviews, only: %i[index new create]
    resources :test_comments, only: %i[index new create show edit update] do
      collection do
        get 'search_content'
        get 'search_user_name'
        get 'search_souvenir'
      end
    end
  end

  #開発のみの使用
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  skip_before_action :require_login, only: %i[sample_quiz]
  before_action :set_category, only: %i[index calculate_score show]
  before_action :set_quiz, only: %i[index calculate_score show]

  def index
    if QuizResult.taken_today(current_user).exists?
      redirect_to category_reviews_path(@category), error: t('.limit')
    else
      render :index
    end
  end

  def calculate_score
    answers = quiz_params

    quiz_result = QuizResult.calculate_and_create_result(
      category_id: params[:category_id],
      user_id: current_user.id,
      answers:
    )

    handle_quiz_result(answers, quiz_result)
  end

  # クイズの結果を表示
  def show
    @quiz_result = current_user.quiz_results.find(params[:id])
    @pass_status = @quiz_result.is_passed ? t('.passed') : t('.failed')
    @category = @quiz_result.test_category
    @quizzes = @quiz_result.related_quizzes

    @user_quiz_answers, @explanations = @quiz_result.user_quiz_answers_with_explanations(current_user).values_at(:user_answers, :explanations)
  end

  def sample_quiz
    @sample_category = TestCategory.find_by(title: "サンプル問題(フィンランド級)") 
    @sample_quiz = @sample_category.quizzes.includes(:quiz_choices) if @sample_category
  end

  private

  def set_category
    @category = TestCategory.find(params[:category_id])
  end

  def set_quiz
    @quizzes = @category.quizzes.includes(:quiz_choices)
  end

  def quiz_params
    params.require(:answers).permit(@quizzes.map { |quiz| quiz.id.to_s })
  end

  def handle_quiz_result(answers, quiz_result)
    @user_answers = answers
    if quiz_result.nil?
      flash.now[:error] = t('.blank')
      render :index, status: :unprocessable_entity and return
    elsif quiz_result.persisted?
      redirect_to category_quiz_path(category_id: params[:category_id], id: quiz_result.id)
    else
      flash.now[:error] = quiz_result.errors.full_messages.to_sentence
      render :index, status: :unprocessable_entity and return
    end
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
  def has_image?(quiz)
    quiz.quiz_choices.any? { |choice| choice.image_url.present? }
  end
end

app/views/quizzes/index.html.erb
<%= content_for(:title, t('.title')) %>
<div class="background-image ">
  <div class="container pt-32 mx-auto">
    <h1 class="md:text-2xl text-xl px-5">勘検定</h1>
    <div class="text-center md:text-5xl text-4xl py-5">
      <p><%= @category.title %>級</p>
    </div>
    <div class="py-5 pr-5 text-right md:text-2xl text-xl underline underline-offset-1">
      <p>氏名：<%= current_user.name %></p>
    </div>
    <div class="container mx-auto mt-10 md:px-10 px-5 py-5 w-2/3 md:text-2xl text-lg rounded-lg bg-neutral-50 bg-opacity-90">
      <ul>
        <li>⚠️分からない問題があったら「勘」で答えること</li>
        <li>⚠️現地にいるイメージをしながら回答すること</li>
        <li>⚠️とにかく楽しむこと！</li>
      </ul>
    </div>
    <div class="md:pt-20 pt-10 px-5 md:px-10">
      <%= form_with url: calculate_score_category_quizzes_path(@category) ,method: :post do |f|%>
        <% @quizzes.each do |quiz| %>
          <div class="py-10 border-dashed border-b-2 border-stone-400">
            <%= simple_format(quiz.content, class:"md:text-3xl text-2xl") %>
            <div class="w-3/5 mx-auto pt-5">
              <%= image_tag(quiz.image_url) if quiz.image_url.present? %>
            </div>
            <% quiz.quiz_choices.each do |choice| %>
              <div class="flex pt-5 px-10 ">
                <div>
                  <%= f.radio_button "answers[#{quiz.id}]", 
                        choice.id, 
                        checked: @user_answers&.dig(quiz.id.to_s)  == choice.id.to_s,
                        class:"w-8 h-8 rounded-full border-2 border-gray-400 cursor-pointer" %>
                </div>
                <div>
                  <%= f.label "answers_#{quiz.id}_#{choice.id}", choice.content, class:"md:text-2xl text-xl" %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
        <div class="container flex justify-center items-center pt-10 pb-10">
          <%= f.submit t('quizzes.index.submit'), class:"btn btn-lg btn-outline bg-amber-300 font-sans", 
                data: { turbo_confirm: t('.reviewed?') } %>
        </div>
      <% end %>
    </div>  
  </div>
</div>

app/views/quizzes/sample_quiz.html.erb
<%= content_for(:title, t('.title')) %>
<div class="background-image">
  <div class="container pt-32 mx-auto">
    <h1 class="text-center md:text-5xl text-4xl py-5 px-16"><%= @sample_category.title %></h1>
    <div class="container mx-auto mt-10 md:px-10 px-5 py-5 w-2/3 md:text-2xl text-lg rounded-lg bg-neutral-50 bg-opacity-90">
      <ul>
        <li>⚠️分からない問題があったら「勘」で答えること</li>
        <li>⚠️現地にいるイメージをしながら回答すること</li>
        <li>⚠️とにかく楽しむこと！</li>
      </ul>
    </div>
    <div class="md:pt-20 pt-10 px-5 md:px-10">
      <% @sample_quiz.each do |quiz| %>
        <div class="py-10 border-dashed border-b-2 border-stone-400">
          <%= simple_format(quiz.content, class:"md:text-3xl text-2xl") %>
          <% quiz.quiz_choices.each do |choice| %>
            <div class="flex pt-5 px-10 space-x-2">
              <div>
                <input type="radio" name="answer_<%= quiz.id %>" class= "w-8 h-8 rounded-full border-2 border-gray-400 cursor-pointer" />
              </div>
              <div>
                <p class="md:text-2xl text-xl"><%= choice.content %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="pb-10 pt-14 flex justify-center">
      <%= link_to t('.continue'), login_path, class:"btn primary btn-lg bg-zinc-700 text-white" %>
    </div>
  </div>
</div>

app/views/quizzes/show.html.erb
<%= content_for(:title, t('.title')) %>
<div class="background-image">
  <div class="container pt-32 mx-auto">
    <h1 class="md:text-2xl text-xl px-5">合格発表</h1>
    <div class="text-center py-10 space-y-5"> 
      <div class="<%= @pass_status == t('.passed') ? 'text-rose-700' : 'text-teal-800' %>">
        <p class="md:text-8xl text-5xl">【<%= @pass_status %>】</p>
      </div>
      <p class="md:text-2xl text-xl px-5">点数：<%= @quiz_result.score %>/100</p>
      <% if @pass_status == t('.passed') %>
        <%= image_tag 'success.png' %>
      <% end %>
    </div>
    <div class="md:text-3xl text-xl flex pb-12 md:px-0 px-5 justify-center">
      <% if @quiz_result.is_passed? %>
        <div class="flex items-center pt-5 ">
          <p>おめでとうございます！<br>
          勘で当てたところはしっかりと復習をしましょう。</p>
          <%=image_tag 'passed_mark.png', class:"w-24" %>
        </div>
      <% else %>
        <div class="flex space-x-5">
          <p class="pt-20">落ち込まないでください！<br>復習をしてもう一度受検をしましょう。</p>
          <% if @pass_status == t('.failed')  %>
              <%= image_tag 'failed.png', class:"w-28" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <!--クイズ一覧を表示-->
    <% @quizzes.each do |quiz| %>
      <div class="container mb-10 py-10 rounded-lg bg-neutral-50 bg-opacity-90">
        <div class="md:px-10 px-5">
          <p class="text-3xl"><%= simple_format(quiz.content, class:"text-2xl") %></p>
          <div class="w-3/5 mx-auto pt-5">
            <%= image_tag(quiz.image_url) if quiz.image_url.present? %>
          </div>
        </div>
        <!--選択肢、ユーザーの回答、正解を表示-->
        <div class="flex md:flex-row flex-col justify-center md:space-x-16 space-x-0 md:space-y-0 space-y-4 px-10 py-10 md:text-xl text-lg">
          <% quiz.quiz_choices.each do |choice| %>
            <div class="flex items-center space-x-2">
              <p><%= choice.content %></p>
              <% if @user_quiz_answers[quiz.id].quiz_choice_id == choice.id %>
                <% if choice.correct_answer %>
                  <p class="text-red-500 font-black">◎</p>
                <% else %>
                  <p class="font-black">❌</p>
                <% end %>
              <% elsif choice.correct_answer? %>
                <p class="font-black text-blue-500 ">✔︎</p>
              <% end %>
            </div>
          <% end %>
        </div>
        <!--解説を表示-->
        <div class="md:text-xl text-lg pt-5 border-dashed border-t-2 border-stone-400 px-10">
          <% quiz.quiz_choices.each do |choice| %>
            <% if choice.correct_answer %>
              <div class="py-5">
                <p><%= simple_format(choice.explanation) %></p>
              </div>
              <div class="w-3/5 mx-auto">
                <%= image_tag(choice.image_url) if choice.image_url.present? %>
              </div>
            <%end %>
          <% end %>
        </div>
      </div>
    <% end %>
    <!--ボタン-->
    <div class="flex justify-center pb-10">
      <% if @quiz_result.is_passed? %>
        <% if params[:from_passed_list] == 'true' %>
          <%= link_to t('defaults.back'), passed_lists_path, class:"btn primary btn-lg bg-zinc-700 text-white" %>
        <% else %>
          <%= link_to t('.souvenir'), new_category_review_path(@category), class: "btn btn-lg btn-outline bg-sky-200" %>
        <% end %>
      <% else %>
        <%= link_to t('.challenge_again'), category_quizzes_path(@category), class: "btn btn-lg btn-outline bg-rose-200" %> 
      <% end %>
    </div>
  </div>
</div>