config/routes.rb
Rails.application.routes.draw do
  root to: "top_pages#top"
  get 'terms', to: 'top_pages#terms'
  get 'policy', to: 'top_pages#policy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  #Line Messaging
  post '/callback', to: 'linebot#callback' 
  
  get 'passed_lists', to: 'passed_lists#index'
  get 'sample_quiz', to: 'quizzes#sample_quiz'

  resources :users, only: %i[new create]
  resources :password_resets, only: %i[new create edit update]
  resource :profile, only: %i[show edit update]
  resources :test_categories, only: %i[index], as: :categories do
    get 'search_result', on: :collection
    
    resources :quizzes, only: %i[index show] do
      post 'calculate_score', on: :collection
    end
    resources :reviews, only: %i[index new create]
    resources :test_comments, only: %i[index new create show edit update] do
      collection do
        get 'search_content'
        get 'search_user_name'
        get 'search_souvenir'
      end
    end
  end

  #開発のみの使用
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/passed_lists_controller.rb
class PassedListsController < ApplicationController
  def index
    @passed_quizzes = current_user.passed_quizzes.order(created_at: :desc)
    @japan_quizzes = @passed_quizzes.select { |quiz| quiz.test_category.region == 'japan' }
    @foreign_quizzes = @passed_quizzes.select { |quiz| quiz.test_category.region == 'foreign' }
    @test_comments = current_user.test_comments
  end
end

app/helpers/passed_lists_helper.rb
module PassedListsHelper
end

app/views/passed_lists/_passed_test.html.erb
<div class="dropdown dropdown-hover bg-stone-400 w-fit rounded-box">
  <label tabindex="0" class="btn m-1"><p><%= passed.test_category.title %>級</p></label>
  <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box">
    <li><%= link_to t('quizzes.show.title'), category_quiz_path(passed.test_category_id, passed.id, from_passed_list: true) %></li>
    <li><%= link_to t('test_comments.show.buddy'), category_test_comments_path(passed.test_category_id, from_passed_list: true)  %></li>
  </ul>
</div>

app/views/passed_lists/index.html.erb
<%= content_for(:title, t('.title')) %>
<div class="background-image">
  <div class="pt-32 md:px-32 px-20 pb-20 mx-auto text-center">
    <h1 class="md:text-4xl text-3xl md:pt-16">合格級一覧</h1>
    <p class="md:text-xl text-base pt-5">＊ 合格した級から結果と仲間一覧をご覧いただけます ＊</p>
    <div class="flex md:flex-nowrap flex-wrap md:space-x-20 md:space-y-0 space-y-24 md:mt-32 mt-20 mx-auto w-full">
      <% if @passed_quizzes.present? %>
        <div class="md:w-1/2 h-fit w-screen">
          <p class="pb-5 md:text-2xl text-xl font-bold">● 日本編 ●</p>
          <div class="text-2xl px-8 py-10 md:flex md:flex-wrap grid grid-cols-2 gap-2 items-center justify-center rounded-lg bg-red-50 shadow-md shadow-slate-500 bg-opacity-90">
            <% if @japan_quizzes.present? %>
              <% @japan_quizzes.each do |passed| %>
                <%= render 'passed_test', passed: passed %>
              <% end %>
            <% else %>
              <p>まだ合格した級はありません。</p>
              <p>🇯🇵</p>
            <% end %>
          </div>
        </div>
        <div class="md:w-1/2 h-fit w-screen">
          <p class="pb-5 md:text-2xl text-xl font-bold">● 海外編 ●</p>
          <div class="text-2xl px-5 py-10 md:flex md:flex-wrap grid grid-cols-2 gap-2 items-center justify-center rounded-lg bg-cyan-50 shadow-md shadow-slate-500 bg-opacity-90">
            <% if @foreign_quizzes.present? %>
              <% @foreign_quizzes.each do |passed| %>
                <%= render 'passed_test', passed: passed %>
              <% end %>
            <% else %>
              <p>まだ合格した級はありません。</p>
              <p>🌎</p>
            <% end %>
          </div>
        </div>
      <% else %>
        <p>まだ合格した級がありません！</p>
      <% end %>
    </div>
  </div>
  <div class="flex justify-center">
    <%=image_tag 'man.png', class:"w-20" %>
  </div>
  <div class="pb-10 flex justify-center">
    <%= link_to t('defaults.back'), categories_path,  class:"btn primary btn-lg bg-zinc-700 text-white" %>
  </div>
</div>