config/routes.rb
Rails.application.routes.draw do
  root to: "top_pages#top"
  get 'terms', to: 'top_pages#terms'
  get 'policy', to: 'top_pages#policy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  #Line Messaging
  post '/callback', to: 'linebot#callback' 
  
  get 'passed_lists', to: 'passed_lists#index'
  get 'sample_quiz', to: 'quizzes#sample_quiz'

  resources :users, only: %i[new create]
  resources :password_resets, only: %i[new create edit update]
  resource :profile, only: %i[show edit update]
  resources :test_categories, only: %i[index], as: :categories do
    get 'search_result', on: :collection
    
    resources :quizzes, only: %i[index show] do
      post 'calculate_score', on: :collection
    end
    resources :reviews, only: %i[index new create]
    resources :test_comments, only: %i[index new create show edit update] do
      collection do
        get 'search_content'
        get 'search_user_name'
        get 'search_souvenir'
      end
    end
  end

  #開発のみの使用
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :test_category
  has_many :quiz_choices, dependent: :destroy
  has_many :user_quiz_answers, dependent: :destroy

  # 特定のカテゴリーのクイズ数をカウント(quiz_result.rbに使用)
  def self.total_by_category(category_id)
    category = TestCategory.find_by(id: category_id)
    return 0 unless category

    where(test_category_id: category.id).count
  end
end

app/models/quiz_choice.rb
class QuizChoice < ApplicationRecord
  belongs_to :quiz
  has_many :user_quiz_answers, dependent: :destroy
end

app/models/quiz_result.rb
class QuizResult < ApplicationRecord
  belongs_to :test_category
  belongs_to :user

  scope :taken_today, ->(user) { where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).where(user_id: user.id).where(is_passed: true) }

  # quizzes/create用のメソッド ここから
  def self.calculate_and_create_result(category_id:, user_id:, answers:)
    return nil if invalid_answers?(answers, category_id)

    count_correct = count_correct_answers(answers)
    save_user_answers(user_id, answers)
    calculate_score_and_save(category_id, user_id, count_correct, answers.keys.length)
  end

  def self.invalid_answers?(answers, category_id)
    count_quizzes = Quiz.total_by_category(category_id)
    answers.empty? || answers.keys.size < count_quizzes
  end

  def self.count_correct_answers(answers)
    correct_choices = QuizChoice.where(quiz_id: answers.keys, correct_answer: true).index_by(&:quiz_id)
    answers.to_h.count { |quiz, choice| correct_choices[quiz.to_i]&.id.to_s == choice }
  end

  def self.save_user_answers(user_id, answers)
    records = answers.to_h.map do |quiz, choice|
      { user_id:, quiz_id: quiz, quiz_choice_id: choice, created_at: Time.current, updated_at: Time.current }
    end
    UserQuizAnswer.insert_all(records)
  end

  def self.calculate_score_and_save(category_id, user_id, count_correct, total_quizzes)
    total_score = (count_correct.to_f * 100) / total_quizzes
    create(
      test_category_id: category_id,
      user_id:,
      score: total_score,
      is_passed: total_score >= 70
    )
  end
  # ここまで

  # quizzes/show用のメソッド(以下2つ)
  def related_quizzes
    test_category.quizzes.includes(:quiz_choices)
  end

  def user_quiz_answers_with_explanations(user)
    quizzes = related_quizzes
    quiz_ids = quizzes.map(&:id)
    user_answers = UserQuizAnswer.where(user_id: user.id, quiz_id: quiz_ids).index_by(&:quiz_id)
    explanations = QuizChoice.where(quiz_id: quiz_ids, correct_answer: true).index_by(&:quiz_id)
    { user_answers:, explanations: }
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :test_category
  has_many :user_review_answers, dependent: :destroy
end

app/models/souvenir_photo.rb
class SouvenirPhoto < ApplicationRecord
  belongs_to :test_category
  has_many :test_comments, dependent: :destroy

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at explanation id image_url name test_category_id updated_at]
  end
end

app/models/test_category.rb
class TestCategory < ApplicationRecord
  has_many :quizzes, dependent: :destroy
  has_many :quiz_results, dependent: :destroy
  has_many :souvenir_photos, dependent: :destroy
  has_many :test_comments, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def self.ransackable_attributes(_auth_object = nil)
    ["title"]
  end
end

app/models/test_comment.rb
class TestComment < ApplicationRecord
  belongs_to :user
  belongs_to :test_category
  belongs_to :souvenir_photo

  validates :content, presence: true, length: { maximum: 48 }

  def self.ransackable_attributes(_auth_object = nil)
    %w[content created_at id souvenir_photo_id test_category_id updated_at user_id]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[souvenir_photo test_category user]
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :user_quiz_answers, dependent: :destroy
  has_many :quizzes, through: :user_quiz_answers
  has_many :quiz_choices, through: :user_quiz_answers
  has_many :quiz_results, dependent: :destroy
  has_many :souvenir_photos, through: :test_comments
  has_many :user_review_answers, dependent: :destroy
  has_many :reviews, through: :user_review_answers
  has_many :test_comments, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, length: { maximum: 100 }
  validates :password, length: { minimum: 5 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true
  validates :remember_me_token, uniqueness: true, allow_nil: true

  # crud_menus.html.erb用のメソッド
  def own?(object)
    id == object.user_id
  end

  # passed_lists用のメソッド
  def passed_quizzes
    quiz_results.includes(:test_category).where(is_passed: true)
  end

  # reviews/create用のメソッド
  def already_reviewed?(category)
    UserReviewAnswer.joins(:review).where(user_id: id, reviews: { test_category_id: category.id }).exists?
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[avatar created_at id name updated_at]
  end
end

app/models/user_quiz_answer.rb
class UserQuizAnswer < ApplicationRecord
  belongs_to :quiz
  belongs_to :user
  belongs_to :quiz_choice
end

app/models/user_review_answer.rb
class UserReviewAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :user_id, uniqueness: { scope: :review_id }

  def self.count_user_answer(category)
    joins(:review)
      .where(review: { test_category_id: category.id })
      .select(:user_id)
      .distinct.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
  {
    site: '勘検定',
    title: content_for(:title),
    description: '日本・海外のあまり知られていないことを検定で出題し、「勘」を使って答えて頂くサービスです。',
    reverse: true,
    keywords: '勘、旅、クイズ、検定、お土産',
    canonical: request.original_url,
    image: image_url('ogp.png'),
    separator: '|',
    noindex: ! Rails.env.production?,

    og: {
      site_name: '勘検定',
      title: :title,
      description: :description,
      type: 'website',
      url: request.original_url,
      image: image_url('ogp.png'),
      locale: 'ja_JP',
    },

    twitter: {
      card: 'summary_large_image',
      image: image_url('ogp.png'),
      site: ''
    }
  }
  end
end

app/helpers/linebot_helper.rb
module LinebotHelper
end

app/helpers/passed_lists_helper.rb
module PassedListsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/quiz_results_helper.rb
module QuizResultsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
  def has_image?(quiz)
    quiz.quiz_choices.any? { |choice| choice.image_url.present? }
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
  def top; end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_after_login_header.html.erb
<header class="fixed top-0 left-0 w-screen bg-color-400 p-2 font-sans">
  <div class="flex items-center justify-between cursor-pointe pr-5">
    <%= link_to image_tag('logo.jpeg', class:'md:w-20 w-12  ml-5'), root_path %>
    <div class="space-x-10 hidden md:flex">
      <%= link_to t('test_categories.index.title'), categories_path, class: "header-button" %>
      <%= link_to t('passed_lists.index.title'), passed_lists_path, class: "header-button" %>
      <div class="dropdown dropdown-bottom dropdown-end hidden md:flex">
        <label tabindex="0" class="btn header-button"><%= t('defaults.my_page') %></label>
        <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-200 rounded-box w-52">
          <li><%= link_to t('profiles.show.title'), profile_path %></li>
          <li><%= link_to (t 'defaults.logout'), logout_path, data: { turbo_method: :delete } %></li>
        </ul>
      </div>
    </div> 

    <!-- スマホサイズ -->
    <div class="dropdown dropdown-left md:hidden">
      <label tabindex="0" class="btn m-1"><i class="fa-solid fa-bars"></i></label>
      <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-200 rounded-box w-52">
        <li><%= link_to t('test_categories.index.title'), categories_path %></li>
        <li><%= link_to t('passed_lists.index.title'),  passed_lists_path %></li>
        <li>
          <%= link_to t('defaults.my_page')%>
          <ul class="dropdown-menu">
            <li><%= link_to "■" + t('profiles.show.title'), profile_path %></li>
            <li><%= link_to "■" + t('defaults.logout'), logout_path, data: { turbo_method: :delete } %></li>
          </ul>
        </li>
      </ul> 
    </div>
  </div>
</header>

app/views/shared/_before_login_header.html.erb
<header class="fixed top-0 left-0 w-screen bg-color-400 p-2 font-sans">
  <div class="flex items-center justify-between cursor-pointe pr-5">
    <%= link_to image_tag('logo.jpeg', class:'md:w-20 w-12 ml-5'), root_path %>
    <div class="space-x-10 hidden md:flex">
      <%= link_to t('quizzes.sample_quiz.title'), sample_quiz_path, class: "header-button" %>
      <%= link_to t('test_categories.index.title'), categories_path, class: "header-button" %>
      <%= link_to t('user_sessions.new.title'), login_path, class: "header-button" %>
    </div>

  <!-- スマホサイズ -->
    <div class="dropdown dropdown-left md:hidden">
      <label tabindex="0" class="btn m-1"><i class="fa-solid fa-bars"></i></label>
      <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-200 rounded-box w-52">
        <li><%= link_to t('quizzes.sample_quiz.title'), sample_quiz_path %></li>
        <%= link_to t('test_categories.index.title'), categories_path %>
        <li><%= link_to t('user_sessions.new.title'), login_path %></li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="bg-red-100 rounded-lg">
    <ul class="list-disc pl-10 text-lg">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% if flash[:success] %>
  <div class="alert border-cyan-700 bg-sky-100 border-double border-4 rounded-none md:text-2xl text-md md:mt-20 pt-24 md:pt-7 flex font-sans">
    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
      <%= flash[:success] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert border-red-800 bg-red-100 border-double border-4 rounded-none md:text-2xl text-md md:mt-20 md:mt-20 pt-24 md:pt-7 flex font-sans">
    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
    <%= flash[:error] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-color-400 mb-0 bottom-0 py-5 w-screen font-sans">
  <div class="flex justify-center space-x-2 footer ">
    <%= link_to t('top_pages.terms.title'), terms_path %>
    <%= link_to t('top_pages.policy.title'), policy_path %>
    <%= link_to "お問い合わせ", "https://forms.gle/GxrbtFnuvVDuSXtNA" %>
  </div>
  <div class="flex justify-center pt-5 text-white text-sm">
    <p>Copyright © 2023 - 勘検定</p>
  </div>
</footer>