config/routes.rb
Rails.application.routes.draw do
  root to: "top_pages#top"
  get 'terms', to: 'top_pages#terms'
  get 'policy', to: 'top_pages#policy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  #Line Messaging
  post '/callback', to: 'linebot#callback' 
  
  get 'passed_lists', to: 'passed_lists#index'
  get 'sample_quiz', to: 'quizzes#sample_quiz'

  resources :users, only: %i[new create]
  resources :password_resets, only: %i[new create edit update]
  resource :profile, only: %i[show edit update]
  resources :test_categories, only: %i[index], as: :categories do
    get 'search_result', on: :collection
    
    resources :quizzes, only: %i[index show] do
      post 'calculate_score', on: :collection
    end
    resources :reviews, only: %i[index new create]
    resources :test_comments, only: %i[index new create show edit update] do
      collection do
        get 'search_content'
        get 'search_user_name'
        get 'search_souvenir'
      end
    end
  end

  #開発のみの使用
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/test_comment.rb
class TestComment < ApplicationRecord
  belongs_to :user
  belongs_to :test_category
  belongs_to :souvenir_photo

  validates :content, presence: true, length: { maximum: 48 }

  def self.ransackable_attributes(_auth_object = nil)
    %w[content created_at id souvenir_photo_id test_category_id updated_at user_id]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[souvenir_photo test_category user]
  end
end

app/controllers/test_comments_controller.rb
class TestCommentsController < ApplicationController
  before_action :set_category, only: %i[index new create show edit update]

  def index
    @q = @category.test_comments.ransack(params[:q])
    @test_comments = @q.result(distinct: true).includes(:user, :souvenir_photo).order(created_at: :desc).page(params[:page]).per(6)
  end

  def new
    @reviewed = current_user.already_reviewed?(@category)
    @test_comment = TestComment.new
    @souvenir = SouvenirPhoto.where(test_category_id: @category.id).order("RANDOM()").first
  end

  def create
    @test_comment = current_user.test_comments.build(test_comment_params)
    if @test_comment.save
      redirect_to category_test_comments_path(@category), success: t('.success')
    else
      @souvenir = SouvenirPhoto.find(test_comment_params[:souvenir_photo_id])
      flash.now[:error] = t('.failed')
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @test_comment = current_user.test_comments.find(params[:id])
    @souvenir = @test_comment.souvenir_photo
  end

  def edit
    @test_comment = current_user.test_comments.find(params[:id])
    @souvenir = @test_comment.souvenir_photo
  end

  def update
    @test_comment = current_user.test_comments.find(params[:id])
    @souvenir = @test_comment.souvenir_photo

    if @test_comment.update(test_comment_params)
      redirect_to category_test_comment_path(@category, @test_comment), success: t('.success')
    else
      flash.now[:error] = t('.failed')
      render :edit, status: :unprocessable_entity
    end
  end

  def search_content
    @test_comments = TestComment.where("content LIKE ?", "%#{params[:q]}%")
    search_results(:content)
  end

  def search_user_name
    @test_comments = TestComment.joins(:user).where("users.name LIKE ?", "%#{params[:q]}%")
    search_results(:user_name)
  end

  def search_souvenir
    @test_comments = TestComment.joins(:souvenir_photo).where("souvenir_photos.name LIKE ?", "%#{params[:q]}%")
    search_results(:souvenir_photo_name)
  end

  def search_results(search_type)
    respond_to do |format|
      format.js { render partial: 'search_result', locals: { test_comments: @test_comments, search_type: } }
    end
  end

  private

  def test_comment_params
    params.require(:test_comment).permit(:content, :souvenir_photo_id, :test_category_id)
  end

  def set_category
    @category = TestCategory.find(params[:category_id])
  end
end

app/helpers/test_comments_helper.rb
module TestCommentsHelper
end

app/views/test_comments/_crud_menus.html.erb
<div>
  <%= link_to edit_category_test_comment_path(category, test_comment), data: { turbo: false } do %>
    <i class="fa-solid fa-pen-to-square"></i>
  <% end %>
</div>

app/views/test_comments/_form.html.erb
<div class="container certification md:pb-20 pb-10 py-5 mx-auto max-w-lg">
  <p class="text-center md:text-2xl text-xl md:pt-12 pt-6 font-black"><%= category.title %>級 合格証明書</p>
  <div class="flex md:space-x-32 space-x-24 items-center pt-2">
    <div class="md:pl-28 pl-20">
      <%= image_tag current_user.avatar.url, class: "md:max-w-sm w-12 border-solid border-2 border-neutral-400 rounded-lg" %>
    </div>
    <p class="md:text-xl text-sm pr-10">氏名：<%= current_user.name %></p>
  </div>
  <%= form_with model: [category, test_comment], url: (test_comment.new_record? ? category_test_comments_path(category) : category_test_comment_path(category, test_comment)) do |f| %>
    <%= render 'shared/error_messages', object: f.object%>
    <%= f.hidden_field :test_category_id, value: category.id %>
    <%= f.hidden_field :souvenir_photo_id, value: @souvenir.id %>
    <div class="md:space-y-5 md:text-lg text-sm px-5 pt-5 text-md">
      <div class="flex flex-col items-center px-10">
        <%= f.label :content, "【" + TestComment.human_attribute_name(:content) + "】" %>
        <%= f.text_area:content, placeholder: t('test_comments.new.example'), class:"input input-bordered md:w-72 w-60 h-28" %>
      </div>
      <div class="flex flex-col items-center">
        <%= f.label :name, "【" + SouvenirPhoto.human_attribute_name(:name) + "】" %>
        <%if souvenir.image_url.present? %>
          <p class="pb-0 px-5"><%= souvenir.name %></p>
          <%= image_tag souvenir.image_url, class: "rounded-lg md:w-44 w-32 md:h-40 h-28" %>
        <% else %>
          <p><%= souvenir.name %></p>
          <%= image_tag "no_image.jpg", class: "rounded-lg md:w-44 w-32 md:h-40 h-28" %>
        <% end %>
      </div>
      <div class="container flex justify-center items-center pt-28 pb-10">
        <%= f.submit test_comment.new_record? ? t('test_comments.new.post') : t('test_comments.new.update'),  class:"btn primary btn-lg bg-zinc-700 text-white"%>
      </div>
    </div>
  <% end %>
</div>


    

app/views/test_comments/_search_form.html.erb
<%= search_form_for @q, url: category_test_comments_path, method: :get, html: { data: { turbo_frame: "comment_list" } } do |f| %>
  <div class="flex justify-center space-x-20">
    <div class="flex flex-col md:flex-row space-x-2 pt-10 md:pt-20 px-5 justify-center">
      <div data-controller="autocomplete" data-autocomplete-url-value="<%= search_content_category_test_comments_path %>" role="combobox">
        <%= f.search_field :content_cont, data: { autocomplete_target: 'input' }, class: "input input-bordered w-60 rounded-lg", placeholder: "コメント" %>
        <%= f.hidden_field :content, data: { autocomplete_target: 'hidden' } %>
        <ul class="list-group" data-autocomplete-target="results"></ul>
      </div>
      <div data-controller="autocomplete" data-autocomplete-url-value="<%= search_user_name_category_test_comments_path %>" role="combobox">
        <%= f.search_field :user_name_cont, data: { autocomplete_target: 'input' }, class: "input input-bordered w-60 rounded-lg", placeholder: "ユーザー名" %>
        <%= f.hidden_field :user_name, data: { autocomplete_target: 'hidden' } %>
        <ul class="list-group" data-autocomplete-target="results"></ul>
      </div>
      <div data-controller="autocomplete" data-autocomplete-url-value="<%= search_souvenir_category_test_comments_path %>" role="combobox">
        <%= f.search_field :souvenir_photo_name_cont, data: { autocomplete_target: 'input' }, class: "input input-bordered w-60 rounded-lg", placeholder: "お土産名" %>
        <%= f.hidden_field :souvenir_photo_name, data: { autocomplete_target: 'hidden' } %>
        <ul class="list-group" data-autocomplete-target="results"></ul>
      </div>
      <div>
        <%= link_to t('test_comments.index.reset'), category_test_comments_path, class: "btn md:btn-md btn-outline bg-color-400 text-white text-base md:mt-0 mt-5" %>
        <%= f.submit t('defaults.search'), class: "btn btn-md btn-outline bg-gray-700 text-white text-base" %>
      </div>
    </div>
  </div>
<% end %>

app/views/test_comments/_search_result.html.erb
<% test_comments.each do |test_comment| %>
  <% if search_type == :content && test_comment.content.present? %>
    <li role="option" data-autocomplete-value="<%= test_comment.id %>" data-autocomplete-label="<%= test_comment.content %>"
                  class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52 rounded-lg w-60">
      <%= test_comment.content %>
    </li>
  <% elsif search_type == :user_name && test_comment.user.name.present? %>
    <li role="option" data-autocomplete-value="<%= test_comment.id %>" data-autocomplete-label="<%= test_comment.user.name %>"
                  class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52 rounded-lg w-60">
      <%= test_comment.user.name %>
    </li>
  <% elsif search_type == :souvenir_photo_name && test_comment.souvenir_photo.present? %>
    <li role="option" data-autocomplete-value="<%= test_comment.id %>" data-autocomplete-label="<%= test_comment.souvenir_photo.name %>"
                  class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52 rounded-lg w-60">
      <%= test_comment.souvenir_photo.name %>
    </li>
  <% end %>
<% end %>

app/views/test_comments/_test_comment.html.erb
<div class="container certification w-fit pb-28 md:pb-20 py-10 md:mx-auto">
  <p class="text-center md:text-2xl text-md md:pt-10 pt-2 font-black"><%= category.title %>級 合格証明書</p>
  <div class="flex items-center space-x-20 md:px-10">
    <div class="pl-16 pt-2 md:pt-10">
      <%= image_tag test_comment.user.avatar.url, class:"md:max-w-sm w-12 border-solid border-2 border-neutral-400 rounded-lg" %>
    </div>
    <p class="text-sm pt-3 pr-14 md:pl-20 text-nowrap">氏名：<%= test_comment.user.name %></p>
  </div>
  <div class="px-5 md:pt-5 md:text-md text-sm font-bold">
    <div class="flex flex-col items-center pt-3">
      <div class="md:text-md text-sm input input-bordered md:w-68 w-56 md:h-28 h-24">
        <%= test_comment.content %>
      </div>
    </div>
    <div class="flex flex-col items-center md:pt-5 pt-1">
      <p>【<%= SouvenirPhoto.human_attribute_name(:name) %>】</p>
      <%if test_comment.souvenir_photo.image_url.present? %>
        <p><%= test_comment.souvenir_photo.name %></p>
        <%= image_tag test_comment.souvenir_photo.image_url, class:"rounded-lg md:min-w-fit w-32 md:h-40 h-20 pt-2" %>
      <% else %>
        <p><%= test_comment.souvenir_photo.name %></p>
        <%= image_tag "no_image.jpg", class: "rounded-lg md:w-44 w-28 md:h-40 h-28" %>
      <% end %>
    </div>
  </div>
  <div class="md:text-4xl text-3xl flex space-x-5 items-center pt-10 pb-20 px-40 md:pl-28">
    <% if current_user.own?(test_comment) %>
      <div>
        <%= link_to "https://twitter.com/share?url=#{root_url}&text=#{category.title}級に合格しました。%0A同じ級に合格したみんなよろしくね🤝&hashtags=勘検定,#{category.title},旅", target: '_blank', data: { toggle: "tooltip", placement: "bottom" }, title: "Xでシェア" do %>
          <i class="fa-brands fa-square-x-twitter"></i>
        <% end %>
      </div>
      <%= render 'crud_menus', test_comment: test_comment, category: category %>
    <% end %>
  </div>
</div>

app/views/test_comments/edit.html.erb
<%= content_for(:title, t('.title')) %>
<div class="background-image">
  <div class="pt-32 md:text-3xl text-2xl mx-auto text-center">
    <h1>コメント編集</h1>
    <% if @souvenir.explanation.present? %>
      <div class="rounded-lg bg-neutral-50 bg-opacity-90 py-3 px-10 w-fit md:mx-auto mt-16 md:text-xl text-base">
        <p class="bg-emerald-100 rounded-full pb-1">お土産：<%= @test_comment.souvenir_photo.name %></p>
        <%= @test_comment.souvenir_photo.explanation.present? ?  @test_comment.souvenir_photo.explanation : "" %>
      </div>
    <% end %>
    <div class="pt-20">
      <%= render 'form', category: @category, souvenir: @souvenir, test_comment: @test_comment %>
    </div>
  </div>
</div>

app/views/test_comments/index.html.erb
<%= content_for(:title, t('.title')) %>
<div class="background-image">
  <div class="container pt-32 mx-auto text-center">
    <h1 class="md:text-4xl text-3xl pb-5 md:pt-20"><%= @category.title %>級に合格した仲間達</h1>

    <!--検索-->
    <%= render 'search_form' %>

    <!-- コメント一覧 -->
    <%= turbo_frame_tag "comment_list" do %>
      <% if @test_comments.present? %>
        <div class="md:grid md:grid-cols-2 md:gap-4 flex flex-wrap place-items-center pt-20 justify-center px-5">
          <%= render @test_comments, category: @category, souvenir: @souvenir %>
        </div>
      <% else %>
        <div class="flex items-center rounded-lg bg-neutral-50 bg-opacity-90 md:p-10 py-10 pl-5 pr-10  mt-10 mb-10 md:mx-auto mx-10 w-fit">
          <%= image_tag 'sorry.png', class: "w-20" %>
          <p class="md:text-2xl text-xl">お探しの内容は見つかりませんでした。</p>
        </div>
      <% end %>
    <% end %>
    <div class="flex justify-center pb-10">
      <% if params[:from_passed_list] == "true" %>
        <%= link_to t('defaults.back'), passed_lists_path, class:"btn primary btn-lg bg-zinc-700 text-white" %>
      <% else %>
        <%= link_to t('test_categories.index.title'), categories_path,  class:"btn primary btn-lg bg-zinc-700 text-white" %>
      <% end %>
    </div>

    <!--ページネーション-->
    <div class="py-10">
      <%= paginate @test_comments %>
    </div>
  </div>
</div>


    

app/views/test_comments/new.html.erb
<%= content_for(:title, t('.title')) %>
<div class="background-image">
  <div class="pt-32 mx-auto text-center ">
    <div class="px-20 md:text-3xl text-xl">
      <p><%= current_user.name %>さんへのお土産は「<%= @souvenir.name %>」です。</p>
      <%= @souvenir.explanation.present? ?  @souvenir.explanation : "" %>
      <p class="text-center pt-16">改めまして、合格おめでとうございます<i class="fa-solid fa-hands-bubbles"></i></p>
    </div>
    <div class="pt-20">
      <%= render 'form', category: @category, souvenir: @souvenir, test_comment: @test_comment %>
    </div>
  </div>
</div>


  

app/views/test_comments/show.html.erb
<%= content_for(:title, t('.title')) %>
<div class="background-image">
  <div class="container pt-32 md:text-3xl text-2xl mx-auto text-center">
    <h1>合格証明書</h1>
    <div class="pt-20">
      <%= render @test_comment, category: @category, souvenir: @souvenir %>
    </div>
  </div>
  <div class="flex justify-center pb-10 pt-5">
    <%= link_to t('.buddy'), category_test_comments_path(@category), class:"btn primary btn-lg bg-zinc-700 text-white" %>
  </div>
</div>


    